site_name: Hiraeth's Wiki
site_url: https://hiraethecho.github.io/wiki/
site_author: hiraeth
site_description: My personal wiki or PKM
repo_name: hiraethecho/wiki
repo_url: https://github.com/hiraethecho/wiki

theme:
  name: 'material'

  features:
    # - content.action.edit
    # - content.action.view
    - content.code.copy
    - navigation.footer
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  - pymdownx.details
  - nl2br
  - admonition
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true
extra:
  status: # 用于标记文档的状态,需要在md文档的元数据中添加status字段
    in-progress: in-progress #进行中的内容
    draft: draft  #草稿状态的内容
  social:
      - icon: material/github
        link: https://github.com/hiraethecho
        name: GitHub

plugins:
  - search
  - blog:
      enabled: false
      post_url_format: "posts/{file}"
      post_excerpt: optional
      archive: true
      categories: true
      categories_url_format: "{slug}"
  - callouts
  - tags:
      tags_file: tags.md
      tags_hierarchy: true
  # - roamlinks
  - rss:
      match_path: .* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

not_in_nav: |
  /tags.md
  /index.md

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
