site_name: Hiraeth's Wiki
site_url: https://hiraethecho.github.io/wiki/
site_author: hiraeth
site_description: My personal wiki
repo_name: hiraethecho/wiki
repo_url: https://github.com/hiraethecho/wiki

theme:
  name: 'material'

  features:
    # - content.action.edit
    # - content.action.view
    - content.code.copy
    - navigation.footer
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.expand
    # - navigation.path
    - navigation.indexes
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  - pymdownx.details
  - nl2br
  - admonition
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  # - callouts
  - tags:
      tags_file: tags.md
      tags_hierarchy: true
  # - roamlinks
  # - blog
  # - rss:
  #     match_path: .* 
  #     date_from_meta:
  #       as_creation: date
  #     categories:
  #       - categories
  #       - tags

not_in_nav: |
  /tags.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
